### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by ghost** [codesandnotes/secure-rest-spring-tut#1]
When I imported this project and run mvn clean install -DskipTests, it gives me following compilation issue. Could you please look at it?

`[ERROR] Failed to execute goal on project secure-rest-spring-tut: Could not resolve dependencies for project codesandnotes:secure-rest-spring-tut:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903, org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:8.1.16.v20140903: Failure to find org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903 in https://repo1.maven.org/maven2 was cached in the local re
pository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project secure-rest-spring-tut: Could not resolve dependencies for project codesandnotes:secure-rest-spring-tut:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903, org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:8.1.16.v20140903: Failure to find org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903 in https://r
epo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project codesandnotes:secure-rest-spring-tut:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903, org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:8.1.16.v20140903: Failure to find org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903 in https://repo1.maven.org/maven2 was cached in the local r
epository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903, org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:8.1.16.v20140903: Failure to find org.eclipse.jetty.websocket:websocket-server:jar:8.1.16.v20140903 in https://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed
or updates are forced
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)`

**Comment by codesandnotes** [comment]
Hello,

I've updated the pom.xml and excluded Jetty's websocket artifacts from
pom.xml: it's not needed, and apparently not available anymore on Maven...

You should be ok now.

Cheers!

**Comment by codesandnotes** [comment]
pom.xml updated. Problematic dependencies removed.
